const productos = [
    {
    id: 1,
    precio:637759 ,
    nombre:"Monitor 24 Benq Zowie XL2411K 144Hz 1ms" ,
    img:"./img/img productos/Monitor 24 Benq Zowie XL2411K 144Hz 1ms.png",
    categoria: "gamer",
    cantidad:1,
   
}, 
{
    id: 2,
    precio:966299 ,
    nombre:"Monitor 24,5 Led Zowie XL2546K-B Dark Grey 240Hz" ,
    img:"./img/img productos/Monitor 24,5 Led Zowie XL2546K-B Dark Grey 240Hz.png",
    categoria: "gamer",
    cantidad:1,
},     {
    id: 3,
    precio:830620 ,
    nombre:"monitor 27 zowie xl2746k" ,
    img:"./img/img productos/monitor 27 zowie xl2746k led.png",
    categoria: "gamer",
    cantidad:1,
},     {
    id: 4,
    precio:1122259 ,
    nombre:"Monitor 27 Benq SW270C 2K IPS HDR10.png" ,
    img:"./img/img productos/Monitor 27 Benq SW270C 2K IPS HDR10.png",
    categoria: "diseño",
    cantidad:1,
},     {
    id: 5,
    precio:650114,
    nombre:"Monitor 27 Zowie XL2731K LED" ,
    img:"./img/img productos/Monitor 27 Zowie XL2731K LED.png",
    categoria: "gamer",
    cantidad:1,
},     {
    id: 6,
    precio:1302500 ,
    nombre:"Monitor 32 Benq 4K IPS HDR10" ,
    img:"./img/img productos/Monitor 32 Benq 4K IPS HDR10.png",
    categoria: "diseño",
    cantidad:1,
},    
{
    id: 7,
    precio:483139 ,
    nombre:"Monitor 27 MSI Optix G271C Curvo VA" ,
    img:"./img/img productos/Monitor 27 MSI Optix G271C Curvo VA 165Hz.png",
    categoria: "diseño",
    cantidad:1,
},     {
    id: 8,
    precio:444499 ,
    nombre:"Monitor 27 MSI Optix G2712 FHD IPS" ,
    img:"./img/img productos/Monitor 27 MSI Optix G2712 FHD IPS 170Hz.png",
    categoria: "gamer",
    cantidad:1,
},     {
    id: 9,
    precio:88009 ,
    nombre:"Soporte Intelaid De Escritorio  VESA 100x100 IT-DBSL.png",
    img:"./img/img productos/Soporte Intelaid De Escritorio  VESA 100x100 IT-DBSL.png",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 10,
    precio:77549 ,
    nombre:"Soporte Intelaid De Escritorio Doble Monito" ,
    img:"./img/img productos/Soporte Intelaid De Escritorio Doble Monitor.png",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 11,
    precio:251099 ,
    nombre:"Soporte Intelaid De Escritorio Setup 2 Moni Camara Microfono Luz IT-SDM" ,
    img:"./img/img productos/Soporte Intelaid De Escritorio Setup 2 Moni Camara Microfono Luz IT-SDM.jpeg",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 12,
    precio:81509 ,
    nombre:"Soporte Intelaid De Techo Telescopico Para TV IT-CBS4" ,
    img:"./img/img productos/Soporte Intelaid De Techo Telescopico Para TV IT-CBS4.png",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 13,
    precio:240425 ,
    nombre:"Soporte Intelaid Doble Monitor 1USB Audio 17 a 32 100x100 IT-DGB2U" ,
    img:"./img/img productos/Soporte Intelaid Doble Monitor 1USB Audio 17 a 32 100x100 IT-DGB2U.jpg",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 14,
    precio:127169,
    nombre:"Soporte Intelaid Extensible 803mm 50Kg IT-TB70" ,
    img:"./img/img productos/Soporte Intelaid Extensible 803mm 50Kg IT-TB70.png",
    categoria: "soporte",
    cantidad:1,
},     {
    id: 15,
    precio:208709  ,
    nombre:"Soporte Intelaid" ,
    img:"./img/img productos/Soporte Intelaid.png",
    categoria: "soporte",
    cantidad:1,
} ,{
    id: 16,
    precio:999114,
    nombre:"Monitor gaming ROG Swift 360Hz PG259QNR" ,
    img:"./img/img productos/Monitor gaming ROG Swift 360Hz PG259QNR.png",
    categoria: "gamer",
    cantidad:1,
}, 

];